
zuul:
  prefix: 
  routes:
    cliente: 
      path: /cliente/**
      serviceId: MsCliente
 
    product: 
      path: /produto/**
      serviceId: MsProduto

    venda: 
      path: /venda/**
      serviceId: MsVenda 
      
    autenticacao: 
      path: /autenticacao/**
      serviceId: MsAutenticacao     

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765


